version: "3.7"

networks: 
    infrastructure:
        driver: bridge

services: 
    messaging-hub:
        container_name: messaging-hub
        env_file: "./.env"
        hostname: messenger 
        networks: 
            infrastructure: {}
        build: 
            context: ./messaging
            args:     
             - ENVMQTTUSER
             - ENVMQTTPASS
        ports: 
            - "1883:1883"
            - "9001:9001"
            - "9002:1883"
    data-acquisition:
        container_name: data-acquisition
        env_file: "./.env"
        hostname: data-acquisition
        networks: 
            infrastructure: {}
        build:
            context: ./data-acquisition
            args:
               - ENVMQTTUSER
               - ENVMQTTPASS
               - ENVOPCUSER
               - ENVOPCPASS
               - MQTTHOSTNAME=messenger
        ports: 
            - "1880:1880"
            - "9000:1880"
    influxdatabase:
        container_name: influxdatabase
        # image: influxdb
        build: 
            context: ./database
            args:
               - DOCKER_INFLUXDB_INIT_MODE=setup
               - DOCKER_INFLUXDB_INIT_USERNAME
               - DOCKER_INFLUXDB_INIT_PASSWORD
               - DOCKER_INFLUXDB_INIT_ORG
               - DOCKER_INFLUXDB_INIT_BUCKET
               - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
        env_file: "./.env"
        hostname: influxdb
        ports: 
            - "8086:8086"
            - "9006:8086"
        networks: 
            infrastructure: {}
        volumes: 
            - type: volume
              source: influxdb-volume
              target: /var/lib/influxdbv2
        # environment: 
        #     - DOCKER_INFLUXDB_INIT_MODE=setup
        #     - DOCKER_INFLUXDB_INIT_USERNAME
        #     - DOCKER_INFLUXDB_INIT_PASSWORD
        #     - DOCKER_INFLUXDB_INIT_ORG
        #     - DOCKER_INFLUXDB_INIT_BUCKET
        #     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
volumes: 
    influxdb-volume: {}
        
